apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: core
          env:
            - name: ENV
              value: "integration"

