apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -int

patches:
  - path: patches/deployment.yaml

images:
  - name: ghcr.io/lootopia-org/core
    newTag: integration

